services:
  # PHP / Laravel Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-react-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    ports:
      - "5173:5173"
    depends_on:
      - mysql

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network

  # MongoDB Service
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecomarket_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      # <--- Add these two lines
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
